int temp, k, x, y;
Console.WriteLine("Введите трехзначное число");
k = Convert.ToInt32(Console.ReadLine());
temp = k;
k = k / 100;
temp = temp % 100;
//x = k / 10;
y = k % 10;
k = temp;
Console.WriteLine($"Полученное трехзначное число:, {k}{y}");
Console.ReadLine();